tests:
  ginkgoLabelFilter: >
    (E2E || Operators || TestHarness || ServiceDefinition) && !Informing
  testHarnesses:
    - quay.io/app-sre/aws-vpce-operator-test-harness
    - quay.io/app-sre/cloud-ingress-operator-test-harness
    - quay.io/app-sre/custom-domains-operator-test-harness
    - quay.io/app-sre/managed-node-metadata-operator-test-harness
    - quay.io/app-sre/managed-upgrade-operator-test-harness
    - quay.io/app-sre/must-gather-operator-test-harness
    - quay.io/app-sre/ocm-agent-operator-test-harness
    - quay.io/app-sre/osd-metrics-exporter-test-harness
    - quay.io/app-sre/rbac-permissions-operator-test-harness
    - quay.io/app-sre/splunk-forwarder-operator-test-harness
    - quay.io/app-sre/route-monitor-operator-test-harness
    - quay.io/app-sre/cloud-ingress-operator-test-harness
  harnessTimeout: 900
